### ISSUE TITLE
Deprecated selector in `atomic-monokai-pro-syntax/index.less`

### ISSUE THREAD

**Issue by justinHensley** [tterb/Atomic-Monokai-Pro-syntax#1]
In `atomic-monokai-pro-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.syntax--source.syntax--css .syntax--entity.syntax--other.syntax--attribute-name.attribute` => `.syntax--source.syntax--css .syntax--entity.syntax--other.syntax--attribute-name.syntax--attribute`

* `.syntax--source.syntax--css .syntax--entity.syntax--other.syntax--attribute-name.id` => `.syntax--source.syntax--css .syntax--entity.syntax--other.syntax--attribute-name.syntax--id`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by tterb** [comment]
I'll take care of this and publish an update today. 
Thanks for the heads up! 👍

**Comment by tterb** [comment]
**Fixed with commit** 36bca2429109a70b9dd20d81c7666d7dc83e5785
