### ISSUE TITLE
Python F-strings are being poorly colorized

### ISSUE THREAD

**Issue by ThatXliner** [tterb/Atomic-Monokai-Pro-syntax#2]
Just look at this:
([Monokai pro](https://github.com/tterb/Atomic-Monokai-Pro-syntax))

<img alt="Monokai pro highlighting" src="https://user-images.githubusercontent.com/66848002/92314166-3cedd900-ef89-11ea-9744-2a805580a65c.png">

Versus this:
([Monokai](https://github.com/kevinsawicki/monokai))

<img alt="Monokai" src="https://user-images.githubusercontent.com/66848002/92314167-40816000-ef89-11ea-9b59-4aa7e5dc71b8.png">
I like the colors. But why?!

By the way, I'm using [MagicPython](https://github.com/MagicStack/MagicPython) for advanced python syntax highlighting.

Here's a suggestion: basically copy [Monokai](https://github.com/kevinsawicki/monokai)'s styles but re-colorize them.

I also wonder if this is the intended design...

**Comment by tterb** [comment]
@ThatXliner I've put up a PR (#3) that I believe adds the requested syntax-highlighting but it would be great if you could pull that branch to confirm the changes since I'm not that familiar with MagicPython.

**Comment by ThatXliner** [comment]
@tterb , can you also add highlighting for raw strings, bytes, and Unicode strings, too?

**Comment by tterb** [comment]
@ThatXliner I've updated the PR to include highlighting for all Python string literals.

**Comment by ThatXliner** [comment]
Hmm, I can’t seem to figure out on how to test the change. I know I should do git clone, git checkout, etc., but Atom won’t add it to it’s “theme path”. Any suggestions?

**Comment by tterb** [comment]
@ThatXliner I believe you can test the PR by cloning the branch and running `apm link -d` in the directory. That should create a symlink for the `atomic-monokai-pro-syntax` package so that Atom will use that local branch.

**Comment by ThatXliner** [comment]
Won't it conflict with the Atomic-Monokai-Pro-syntax theme I already have?
