### ISSUE TITLE
Syntax theme overrides my One Dark Tab color

### ISSUE THREAD

**Issue by ThatXliner** [tterb/Atomic-Monokai-Pro-syntax#4]

**Comment by ThatXliner** [comment]
Wait, I just realized that this may have been intentional design. Please document it in the README because my first impression was that I thought that it was a bug.

**Comment by tterb** [comment]
@ThatXliner I believe that is actually a feature of the One-Dark UI-theme that allows it to adapt the interface colors to match the active syntax theme. The only change that this syntax-theme makes to the editor is that it adapts the git-status gutter colors to match the syntax colors.
